apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-red
    hasuraService: custom
  name: node-red
  namespace: edison-ts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      volumes:
      - name: node-red-pv-storage
      persistentVolumeClaim:
        claimName: node-red-pvc
      containers:
      - image: node-red/node-red:1.0.4-12-minimal
        imagePullPolicy: IfNotPresent
        name: node-red
        env:
        - name: TZ
          value: UTC
        - name: NODE_RED_ENABLE_SAFE_MODE
          value: "false"
        - name: NODE_RED_ENABLE_PROJECTS
          value: "false"
        - name: NODE_OPTIONS
        - name: FLOWS
          value: flows.json
        ports:
        - containerPort: 1880
          protocol: TCP
        resources: {}
      volumeMounts:
        - mountPath: "/data"
          name: node-red-pv-storage
          persistentVolumeClaim:
            claimName: node-red-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-red
  name: node-red
  namespace: edison-ts
spec:
  ports:
  - protocol: TCP
    port: 1880
    targetPort: 1880
  selector:
    app: node-red
  type: ClusterIP
